### PR TITLE
New update, now with reporter functionality via MS

### PR DESCRIPTION
**Pull request by angussidney**
Also has fixed authentication issues

### CODE REVIEW

**Comment by angussidney** [comment]
I'm not good with merge conflics; can someone else with git skills merge please?

**Comment by Undo1** [comment]
Yuck, this'll be hard. Usually one wants to shy away from mass indentation changes/fixes unless you're doing them on their own. I'll probably end up doing this (unless someone else beats me to it), but it'll be a while before I have the time and motivation.

**Comment by ArtOfCode-** [comment]
I'm tempted to just do an overwrite of everything with this version.

**Comment by hichris1234** [comment]
The main problem here is that your master is behind Charcoal-SE/master -- your first two commits should not be in this PR.

Also, there's already 1.3.1 released -- seems like you should bump the version number.

**Comment by ArtOfCode-** [comment]
git checkout fixup
    cp fdsc.user.js ../fdsc.user.js.tmp
    git merge master
    git reset --hard origin/master
    mv ../fdsc.user.js.tmp fdsc.user.js
    git commit -am "Fix merge conflict (take fixup)"
    git push origin master

Disclaimer: this exact sequence of commands may or may not actually work. If nobody else beats me to it, I'll try them tomorrow evening, UTC.

**Comment by angussidney** [comment]
Since the two commits on master were meant to be a temporary revert anyway, I think it would be a good idea to force merge into master and avoid all of these merge conflicts.

**Comment by teward** [comment]
This needs a version bump either way to make upgrading by userscript managers work - `1.3.1 == 1.3.1` so upgrades won't work or be processed even if this is merged.  (We're currently at 1.3.1)

**Comment by ArtOfCode-** [comment]
git merge -X theirs fixup

**Pull request merged**
