### PR TITLE
Fix edit icon appearing in post

### PR DESCRIPTION
**Pull request by CalvT**

### CODE REVIEW

**Comment by CalvT** [comment]
Just for a bit of context - the image below happened, and so this is to fix that

Screenshot

**Comment by Cerbrus** [comment]
I'm currently on a short weekend away.
I'll look at it this monday.

Michiel Dommerholt.

**Comment by angussidney** [comment]
@Cerbrus you may want to remove your signature from your emails in future before sending :) I've edited it out for you.

**Comment by Cerbrus** [comment]
Derp, thanks

**Pull request merged**
