### PR TITLE
Fix the error with feedback not being sent if the Ajax call hasn't finished yet

### PR DESCRIPTION
**Pull request by Gothdo**
This delays the decision whether to send feedback or not until the Ajax call to check if the post has been reported by Smokey has finished. See http://chat.stackexchange.com/transcript/message/34174179#34174179

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Heh, and there was me hoping angus would review it so I wouldn't have to remember the code I wrote six months ago :) Gimme a minute.

**Comment by angussidney** [comment]
Yeah, not knowledgable enough about promises etc to be able to properly review this. Sorry :)

**Comment by angussidney** [comment]
Also, before you bump the version number, I have some bug fixes which I'd like to merge in

**Comment by ArtOfCode-** [comment]
Waiting on @Gothdo to confirm that he's tested this. I'm happy with the code, so if it's tested and working then we can merge.

**Comment by Gothdo** [comment]
@ArtOfCode- I tested it, you can merge.

**Comment by ArtOfCode-** [comment]
@angussidney merge away

**Pull request merged**
