### PR TITLE
Collapse "deleted" reports

### PR DESCRIPTION
**Pull request by Cerbrus**
Don't show 2 lines for deleted ("handled") reports,
Expand them again on hover.

What do you think, @Glorfindel83 / @j-f1?

### CODE REVIEW

**Comment by Cerbrus** [comment]
See also the dicussion here, @j-f1:
http://chat.stackexchange.com/transcript/message/35944173#35944173

We kinda came to a "meh, maybe not" conclusion.

**Comment by j-f1** [comment]
Looks good to me, but I’ll give it a quick check this evening before merging.

**Comment by Cerbrus** [comment]
@j-f1: This doesn't seem to be working all the time, since some messages appear to have a `min-height` set:

capture

**Comment by angussidney** [comment]
Repro'd

**Comment by Fortunate-MAN** [comment]
Also reproduced on Firefox 45.0 on Ubuntu.

**Comment by j-f1** [comment]
@Cerbrus those ones have a timestamp, so I’m making the icons stay on the next line to avoid overlap.

**Pull request merged**
